version: '3.8' #version of docker compose
services:
  java-maven-app:
    image: golfpongtarin/demo-app:java-maven-1.0
    ports:
      - 8080:8080
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
        - POSTGRES_PASSWORD:my-pwd
