version: '3.8' #version of docker compose
services:
  java-maven-app:
    image: "golfpongtarin/demo-app:${TAG}"
    ports:
      - '8080:8080'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
